package com.bernelius.abrechnung.config

val builtinThemes =
    listOf(
        ConfigTheme(
            name = "retro-glitch",
            primary = "#ff00ff",
            secondary = "#00ffff",
            tertiary = "#ffff00",
            success = "#00ff00",
            error = "#ff0000",
            warning = "#ff8800",
            info = "#0000ff",
        ),
        ConfigTheme(
            name = "blood-moon",
            primary = "#ff4d4d",
            secondary = "#a30000",
            tertiary = "#660000",
            success = "#b8e994",
            error = "#ff0000",
            warning = "#f8c291",
            info = "#6a89cc",
        ),
        ConfigTheme(
            name = "catppuccin-mocha-rouge",
            primary = "#eba0ac",
            secondary = "#cba6f7",
            tertiary = "#94e2d5",
            success = "#a6da95",
            error = "#f5e0dc",
            warning = "#f9e2af",
            info = "#89b4fa",
        ),
        ConfigTheme(
            name = "deep-forest",
            primary = "#2ecc71",
            secondary = "#27ae60",
            tertiary = "#16a085",
            success = "#7cfc00",
            error = "#e74c3c",
            warning = "#f1c40f",
            info = "#3498db",
        ),
        ConfigTheme(
            name = "neon",
            primary = "#00ff9f",
            secondary = "#00b8ff",
            tertiary = "#bd00ff",
            success = "#39ff14",
            error = "#ff003c",
            warning = "#ffe700",
            info = "#00f0ff",
        ),
        ConfigTheme(
            name = "frozen-wasteland",
            primary = "#f0f8ff",
            secondary = "#708090",
            tertiary = "#00ced1",
            success = "#00ff7f",
            error = "#ff1493",
            warning = "#e0ffff",
            info = "#191970",
        ),
        ConfigTheme(
            name = "toxic-sludge",
            primary = "#adff2f",
            secondary = "#8b4513",
            tertiary = "#4b5320",
            success = "#00fa9a",
            error = "#ff4500",
            warning = "#ffd700",
            info = "#7fff00",
        ),
        ConfigTheme(
            name = "solar-flare",
            primary = "#ff3300",
            secondary = "#ff00ff",
            tertiary = "#5e00ff",
            success = "#ccff00",
            error = "#ffffff",
            warning = "#ffcc00",
            info = "#191970",
        ),
    )
