/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

import java.time.Duration

plugins {
    alias(libs.plugins.kotlin.jvm)
    id("org.jetbrains.kotlin.plugin.serialization") version "2.3.20-RC2"
    id("com.gradleup.shadow") version "9.3.0"
    id("org.jlleitschuh.gradle.ktlint") version "14.0.1"
    id("org.graalvm.buildtools.native") version "0.11.5"
    id("org.jetbrains.kotlinx.kover") version "0.9.8"
    application
}

ktlint {
    version.set("1.8.0")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    //db
    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation("org.flywaydb:flyway-core:12.3.0")
    implementation("org.flywaydb:flyway-database-postgresql:12.3.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.jetbrains.exposed:exposed-java-time:1.0.0")
    implementation("org.jetbrains.exposed:exposed-r2dbc:1.0.0")
    implementation("org.xerial:sqlite-jdbc:3.51.2.0")
    implementation("org.postgresql:postgresql:42.7.10")
    //logging
    implementation("ch.qos.logback:logback-classic:1.5.32")
    implementation("com.github.ajalt.mordant:mordant:3.0.2")
    // optional extensions for running animations with coroutines
    implementation("com.github.ajalt.mordant:mordant-coroutines:3.0.2")
    // coroutines for async operations
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
    // toml support
    implementation("com.akuleshov7:ktoml-core:0.7.1")
    // figlet
    implementation("com.github.lalyos:jfiglet:0.0.9")
    // pdf export
    implementation("com.github.librepdf:openpdf:3.0.3")
    // e-mail
    implementation("org.eclipse.angus:jakarta.mail:2.1.0-M1")
    // audio — LWJGL OpenAL + STB Vorbis
    val lwjglVersion = "3.4.1"
    val lwjglNatives = listOf("natives-linux", "natives-macos", "natives-macos-arm64", "natives-windows")

    implementation("org.lwjgl:lwjgl:$lwjglVersion")
    implementation("org.lwjgl:lwjgl-openal:$lwjglVersion")
    implementation("org.lwjgl:lwjgl-stb:$lwjglVersion")
    for (native in lwjglNatives) {
        runtimeOnly("org.lwjgl:lwjgl:$lwjglVersion:$native")
        runtimeOnly("org.lwjgl:lwjgl-openal:$lwjglVersion:$native")
        runtimeOnly("org.lwjgl:lwjgl-stb:$lwjglVersion:$native")
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(24) } }

application {
    // Define the main class for the application.
    mainClass = "com.bernelius.abrechnung.AppKt"
}

tasks.named<Test>("test") {
    timeout.set(Duration.ofSeconds(30))
    useJUnitPlatform()

    testLogging {
        events("failed")
        showExceptions = true
        showStackTraces = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = false
    }

    val RESET = "\u001B[0m"
    val GREEN = "\u001B[32m"
    val RED = "\u001B[31m"
    val YELLOW = "\u001B[33m"

    afterTest(object : groovy.lang.Closure<Any>(this) {
        @Suppress("UNCHECKED_CAST")
        fun doCall(descriptor: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {
            val (color, status) = when {
                result.failedTestCount > 0 -> RED to "FAIL"
                result.skippedTestCount > 0 -> YELLOW to "SKIP"
                result.testCount > 0 -> GREEN to "PASS"
                else -> RESET to "NONE"
            }

            val className = descriptor.className?.substringAfterLast(".") ?: ""
            val methodName = descriptor.displayName?.substringBefore("(") ?: ""
            println("$color[$status]$RESET $className.$methodName")
        }
    })

    afterSuite(object : groovy.lang.Closure<Any>(this) {
        @Suppress("UNCHECKED_CAST")
        fun doCall(descriptor: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {
            if (descriptor.parent == null) {
                val (color, status) = when {
                    result.failedTestCount > 0 -> RED to "FAILED"
                    else -> GREEN to "PASSED"
                }
                println()
                println(
                    "${color}Test ${status}: ${result.testCount} tests, " +
                        "${result.failedTestCount} failed, " +
                        "${result.skippedTestCount} skipped$RESET",
                )
            }
        }
    })
}

graalvmNative {
    toolchainDetection.set(false)
    binaries {
        named("main") {
            buildArgs.add("--enable-url-protocols=https,http")
            buildArgs.add("--enable-native-access=ALL-UNNAMED")
        }
    }
}

tasks.register<Exec>("buildNativeImage") {
    group = "build"
    description = "Build GraalVM native image"
    workingDir(rootProject.rootDir)
    commandLine("${System.getProperty("user.home")}/.sdkman/candidates/java/24-graal/bin/gradlew", ":app:nativeRun", "--no-daemon")
}

tasks {
    shadowJar {
        archiveBaseName.set("abrechnung")
        mergeServiceFiles {
            include("META-INF/services/**")
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
    }
}
