/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

import java.time.Duration

plugins {
    alias(libs.plugins.kotlin.jvm)
    id("org.jetbrains.kotlin.plugin.serialization") version "2.3.20-RC2"
    id("com.gradleup.shadow") version "9.3.0"
    id("org.jlleitschuh.gradle.ktlint") version "14.0.1"
    id("org.graalvm.buildtools.native") version "1.0.0"
    id("org.jetbrains.kotlinx.kover") version "0.9.8"
    application
}

ktlint {
    version.set("1.8.0")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    //db
    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation("org.flywaydb:flyway-core:12.3.0")
    implementation("org.flywaydb:flyway-database-postgresql:12.3.0")
    implementation("com.zaxxer:HikariCP:7.0.2")
    implementation("org.jetbrains.exposed:exposed-java-time:1.0.0")
    implementation("org.jetbrains.exposed:exposed-r2dbc:1.0.0")
    implementation("org.xerial:sqlite-jdbc:3.51.2.0")
    implementation("org.postgresql:postgresql:42.7.10")
    //logging
    implementation("ch.qos.logback:logback-classic:1.5.32")
    implementation("com.github.ajalt.mordant:mordant:3.0.2")
    // optional extensions for running animations with coroutines
    implementation("com.github.ajalt.mordant:mordant-coroutines:3.0.2")
    // coroutines for async operations
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
    // toml support
    implementation("com.akuleshov7:ktoml-core:0.7.1")
    // figlet
    implementation("com.github.lalyos:jfiglet:0.0.9")
    // pdf export
    implementation("com.github.librepdf:openpdf:3.0.3")
    // e-mail
    implementation("org.eclipse.angus:jakarta.mail:2.1.0-M1")
    // audio — LWJGL OpenAL + STB Vorbis
    val lwjglVersion = "3.4.1"
    val lwjglNatives = listOf("natives-linux", "natives-macos", "natives-macos-arm64", "natives-windows")

    implementation("org.lwjgl:lwjgl:$lwjglVersion")
    implementation("org.lwjgl:lwjgl-openal:$lwjglVersion")
    implementation("org.lwjgl:lwjgl-stb:$lwjglVersion")
    for (native in lwjglNatives) {
        implementation("org.lwjgl:lwjgl:$lwjglVersion:$native")
        implementation("org.lwjgl:lwjgl-openal:$lwjglVersion:$native")
        implementation("org.lwjgl:lwjgl-stb:$lwjglVersion:$native")
    }
    // Windows natives for native image - runtime to ensure bundling
    runtimeOnly("org.lwjgl:lwjgl:$lwjglVersion:natives-windows")
    runtimeOnly("org.lwjgl:lwjgl-openal:$lwjglVersion:natives-windows")
    runtimeOnly("org.lwjgl:lwjgl-stb:$lwjglVersion:natives-windows")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
        vendor = JvmVendorSpec.GRAAL_VM
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.bernelius.abrechnung.AppKt"
}

tasks.named<Test>("test") {
    timeout.set(Duration.ofSeconds(30))
    useJUnitPlatform()

    testLogging {
        events("failed")
        showExceptions = true
        showStackTraces = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = false
    }

    val RESET = "\u001B[0m"
    val GREEN = "\u001B[32m"
    val RED = "\u001B[31m"
    val YELLOW = "\u001B[33m"

    afterTest(object : groovy.lang.Closure<Any>(this) {
        @Suppress("UNCHECKED_CAST")
        fun doCall(descriptor: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {
            val (color, status) = when {
                result.failedTestCount > 0 -> RED to "FAIL"
                result.skippedTestCount > 0 -> YELLOW to "SKIP"
                result.testCount > 0 -> GREEN to "PASS"
                else -> RESET to "NONE"
            }

            val className = descriptor.className?.substringAfterLast(".") ?: ""
            val methodName = descriptor.displayName?.substringBefore("(") ?: ""
            println("$color[$status]$RESET $className.$methodName")
        }
    })

    afterSuite(object : groovy.lang.Closure<Any>(this) {
        @Suppress("UNCHECKED_CAST")
        fun doCall(descriptor: org.gradle.api.tasks.testing.TestDescriptor, result: org.gradle.api.tasks.testing.TestResult) {
            if (descriptor.parent == null) {
                val (color, status) = when {
                    result.failedTestCount > 0 -> RED to "FAILED"
                    else -> GREEN to "PASSED"
                }
                println()
                println(
                    "${color}Test ${status}: ${result.testCount} tests, " +
                        "${result.failedTestCount} failed, " +
                        "${result.skippedTestCount} skipped$RESET",
                )
            }
        }
    })
}

graalvmNative {
    // Metadata repository disabled - versions >= 0.3.33 use new format incompatible with plugin 1.0.0
    metadataRepository {
        enabled.set(false)
    }
    binaries {
        named("main") {
            imageName.set("abrechnung") 
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(24))
                vendor.set(JvmVendorSpec.GRAAL_VM)
            })
            buildArgs.add("--enable-url-protocols=https,http")
            buildArgs.add("--enable-native-access=ALL-UNNAMED")
            buildArgs.add("-H:+AddAllCharsets")
            // Suppress sun.misc.Unsafe deprecation warnings from LWJGL
            buildArgs.add("-J--sun-misc-unsafe-memory-access=allow")
            // HikariCP and Logback need build-time initialization for GraalVM native image
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.HikariConfig")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.HikariDataSource")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.pool.HikariPool")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.pool.PoolBase")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.util.DriverDataSource")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.util.PropertyElf")
            buildArgs.add("--initialize-at-build-time=com.zaxxer.hikari.util.UtilityElf")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.Logger")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.Level")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.LoggerContext")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.spi.LogbackServiceProvider")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.spi.TurboFilterList")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.spi.LoggerContextVO")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.spi.AppenderAttachableImpl")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.BasicStatusManager")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.COWArrayList")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.ConsoleAppender")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.OutputStreamAppender")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.encoder.LayoutWrappingEncoder")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.pattern.PatternLayoutEncoderBase")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.PatternLayout")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.encoder.PatternLayoutEncoder")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.helpers.CyclicBuffer")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.spi.LogbackLock")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.ContextBase")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.AppenderBase")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.joran.spi.ConsoleTarget")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.joran.spi.ConsoleTarget\$1")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.joran.spi.ConsoleTarget\$2")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.OutputStreamAppender")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.UnsynchronizedAppenderBase")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.status.InfoStatus")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.status.Status")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.util.LogbackMDCAdapter")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.BasicConfigurator")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.util.ContextInitializer")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.layout.TTLLLayout")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.pattern.ThrowableProxyConverter")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.SimpleTimeBasedGuard")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.ReentryGuard")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.ReentryGuard\$ReentryGuardImpl")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.CachingDateFormatter")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.util.CachingDateFormatter\$CacheTuple")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.classic.util.ContextInitializer\$1")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.spi.ContextAwareImpl")
            buildArgs.add("--initialize-at-build-time=ch.qos.logback.core.spi.FilterAttachableImpl")
            // LWJGL needs run-time initialization (requires actual audio hardware)
            buildArgs.add("--initialize-at-run-time=org.lwjgl")
            buildArgs.add("--initialize-at-run-time=org.lwjgl.openal")
            buildArgs.add("--initialize-at-run-time=org.lwjgl.stb")
            buildArgs.add("--initialize-at-run-time=org.lwjgl.system")
        }

        // Windows launcher with embedded icon - only configured on Windows
        if (System.getProperty("os.name").lowercase().contains("windows")) {
            create("launcher") {
                imageName.set("abrechnung-launcher")
                mainClass.set("com.bernelius.abrechnung.launcher.WindowsLauncherKt")
                javaLauncher.set(javaToolchains.launcherFor {
                    languageVersion.set(JavaLanguageVersion.of(24))
                    vendor.set(JvmVendorSpec.GRAAL_VM)
                })
                buildArgs.add("-H:Icon=${file("src/main/resources/img/abrechnung_dllar_logo.ico").absolutePath}")
                buildArgs.add("--no-fallback")
            }
        }
    }
}

val isWindows = System.getProperty("os.name").lowercase().contains("windows")

val graalvmHome = providers.gradleProperty("graalvmHome").orElse("").get()

// GraalVM Community has native-image in lib/svm/bin/ instead of bin/
// This task creates a symlink to make it work with the native plugin
tasks.register<Exec>("setupGraalVMCommunity") {
    group = "build"
    description = "Create symlink for native-image in GraalVM Community"

    val javaLauncher = graalvmNative.binaries.named("main").get().javaLauncher.get()
    val graalvmHomeDir = if (graalvmHome.isEmpty()) {
        javaLauncher.executablePath.asFile.parentFile.parentFile
    } else {
        file(graalvmHome)
    }
    val binDir = graalvmHomeDir.resolve("bin")
    val svmBinDir = graalvmHomeDir.resolve("lib/svm/bin")
    val nativeImageLink = binDir.resolve("native-image")
    val nativeImageReal = svmBinDir.resolve("native-image")

    onlyIf {
        // Skip on Windows - native-image.cmd is already in bin/
        // Only create symlink if the real binary exists but the link doesn't
        !isWindows && nativeImageReal.exists() && (!nativeImageLink.exists() || nativeImageLink.length() == 0L)
    }

    commandLine("ln", "-sf", nativeImageReal.absolutePath, nativeImageLink.absolutePath)

    doFirst {
        logger.lifecycle("Setting up GraalVM Community native-image symlink")
        logger.lifecycle("  From: ${nativeImageReal.absolutePath}")
        logger.lifecycle("  To: ${nativeImageLink.absolutePath}")
    }
}

tasks.named("nativeCompile") {
    dependsOn("setupGraalVMCommunity")

    if (isWindows) {
        finalizedBy("nativeCompileLauncher")
    }
}

// Configure the Windows launcher task when on Windows
if (isWindows) {
    tasks.named("nativeCompileLauncher") {
        group = "build"
        description = "Build Windows launcher executable with embedded icon"

        doLast {
            val outputDir = layout.buildDirectory.dir("native/nativeCompile").get().asFile
            val launcherExe = outputDir.resolve("abrechnung-launcher.exe")
            logger.lifecycle("Windows launcher built: ${launcherExe.absolutePath}")
        }
    }
}

tasks.register("buildNativeImage") {
    group = "build"
    description = "Build GraalVM native image"
    dependsOn("nativeCompile")
}

tasks {
    shadowJar {
        archiveBaseName.set("abrechnung")
        mergeServiceFiles {
            include("META-INF/services/**")
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
        // Add JVM arguments to manifest to suppress sun.misc.Unsafe warnings at runtime
        manifest {
            attributes(
                "Main-Class" to "com.bernelius.abrechnung.AppKt",
                "Multi-Release" to "true"
            )
        }
    }
}

// Configure the application plugin to pass JVM args when running
application {
    applicationDefaultJvmArgs = listOf("--sun-misc-unsafe-memory-access=allow")
}
